# Generated by Django 5.2.3 on 2025-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
