# Generated by Django 5.2 on 2025-07-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_order_address_order_full_name_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_expiration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
