# Generated by Django 5.2.3 on 2025-07-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_order_card_expiration_order_card_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/covers/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='founding_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='history',
            field=models.TextField(blank=True, help_text='Brief history of the brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='owner_bio',
            field=models.TextField(blank=True, help_text='Brief bio of the brand owner'),
        ),
        migrations.AddField(
            model_name='brand',
            name='owner_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/owners/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
